Ss/completeness
carnall-farrar/tim-tam-repo pull request #15
Opened 2024-12-09 11:48 UTC by sarmsha

Created completeness_utils.py file and made changes to the DQ checklist markdown.

2024-12-09 11:51 UTC, becgr4y requested changes

2024-12-09 11:51 UTC, becgr4y commented on DQ_toolkit/completeness_utils.py
> +}
can you give an example of how this should be formatted?

2024-12-09 11:51 UTC, rami1207 approved these changes

2024-12-09 11:52 UTC, rami1207 requested changes
sorry, I haven't seen Bec's comment before the approval, retracted the approval

2024-12-16 09:06 UTC, sarmsha reviewed
I have included an example of how the missing_values dict should be formatted - there were no other comments.

2024-12-17 13:29 UTC, becgr4y approved these changes

2024-12-18 10:27 UTC, rami1207 approved these changes

2024-12-18 10:27 UTC, merged